### ISSUE TITLE
Investigate how notifications work in Android 

### ISSUE THREAD

**Issue by elenawzy** [uoftblueprint/the-period-purse-2023#11]
Research and find the best way to enable notifications for the user in the settings page. There should be options for a daily, weekly, and monthly reminder, and the user should be able to choose what time they want the notifications to be sent. This is for notifying the user to log their symptoms. There is no need to implement this yet but feel free to play around with various methods!

- [x] Decide on a way to send user notifications

**Comment by Manpreet-Bhatti** [comment]
Some links I found that'll be helpful when creating notifications:

https://developer.android.com/develop/ui/views/notifications/build-notification
https://medium.com/@rajnishsuryavanshi223/notifications-on-android-with-kotlin-extention-function-e7557d413568
https://medium.com/wolox/handling-android-notifications-kotlin-cb2e292101a3
https://www.geeksforgeeks.org/notifications-in-kotlin/
https://www.geeksforgeeks.org/android-progress-notifications-in-kotlin/
https://stackoverflow.com/questions/65971302/notification-in-kotlin-repeating-every-day-at-the-same-time
https://developer.android.com/reference/kotlin/android/app/AlarmManager
https://developer.android.com/reference/kotlin/android/content/BroadcastReceiver
https://developer.android.com/training/scheduling/alarms

The general idea is to place our notification into a notification channel (vital step) so that users are allowed to disable specific "channels" of our notification instead of disabling it altogether. Next, we need to declare permissions in our app's manifest file that users can accept or decline. Lastly, we use the `NotificationCompat` API to start building the actual notification. The rest is semantic and building-block work such as creating expandable notifications, time-sensitive notifications, etc.

In regards to recurring notifications, we'd have to implement an alarm-type methodology. This requires `AlarmManager` which allows the application to be scheduled to run (aka notify); this will then need to be broadcasted using `BroadcastReceiver`. Since it'd be best for our notifications to run without much _work_ from the user, we'd also implement something called a `BootReceiver`, again using `BroadcastReceiver`, which would allow our scheduled notifications to run without the need to launch the app at least once after a reboot (will be triggered immediately after a reboot).

Let me know your thoughts and if you'd like more sources/research!

**Comment by Manpreet-Bhatti** [comment]
@elenawzy @leowrites bumping for review 😅 (I wish I could create PRs without the need of a commit)

**Comment by elenawzy** [comment]
Wow this is really in depth! It looks good 🤩 thanks!
